### ISSUE TITLE
Integer scale factor

### ISSUE THREAD

**Issue by vadosnaprimer** [zb3/freej2me#8]
Is there a way to not make the emulator window occupy all the available width or height of my desktop? The most common approach to this issue is allowing the user to set an integer scale factor, because fractional ones result in distortions due to nearest neighbor interpolation, and it's nearly impossible to resize it manually to not distort (and I don't need it to be bigger than 1x anyway).

**Comment by zb3** [comment]
Try using the `--scale` / `-s` option. Does it work?
```
java -jar freej2me.jar -s 2 game.jar
```
It should also be possible to change the scale dynamically by plus/minus keys

**Comment by vadosnaprimer** [comment]
Oh +/- is perfect, thanks!

`-s` works fine too, even without game path.

I don't think those are mentioned in the docs tho?

**Comment by zb3** [comment]
I've briefly mentioned them in the docs in https://github.com/zb3/freej2me/commit/f48bd7b4db455a0dedbe01963156fc01f28f60f9
